--TEST--
Torture the T_END_NOWDOC rules (nowdoc)
--FILE--
<?php

function fn1373403709()
{
    require_once 'nowdoc.inc';
    print <<<'ENDOFNOWDOC'
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;

ENDOFNOWDOC;
    $x = <<<'ENDOFNOWDOC'
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;

ENDOFNOWDOC;
    print "{$x}";
}
fn1373403709();
--EXPECT--
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;

