--TEST--
Torture the T_END_NOWDOC rules (nowdoc)
--FILE--
<?php

function fn607370093()
{
    require_once 'nowdoc.inc';
    print <<<'ENDOFNOWDOC'
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;

ENDOFNOWDOC;
    $x = <<<'ENDOFNOWDOC'
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;

ENDOFNOWDOC;
    print "{$x}";
}
fn607370093();
--EXPECT--
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;
ENDOFNOWDOC    ;
    ENDOFNOWDOC;
ENDOFNOWDOC    
    ENDOFNOWDOC
$ENDOFNOWDOC;

